# Generated by Django 4.2.1 on 2023-07-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_celebrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityRTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('about', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Celebrity',
            new_name='CelebrityLTR',
        ),
    ]
