# Generated by Django 4.2.1 on 2023-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_celebrityrtl_rename_celebrity_celebrityltr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CelebrityLTR',
            new_name='Celebrity',
        ),
        migrations.DeleteModel(
            name='CelebrityRTL',
        ),
    ]
