# Generated by Django 4.2.1 on 2023-07-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_celebrityltr_celebrity_delete_celebrityrtl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
