# Generated by Django 4.2.1 on 2023-07-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_fancard'),
    ]

    operations = [
        migrations.AddField(
            model_name='fancard',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
