# Generated by Django 4.2.1 on 2023-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_fancard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FancardApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('celebrity', models.CharField(max_length=100)),
            ],
        ),
    ]
