# Generated by Django 4.2.1 on 2023-08-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_fancardapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='fancardapp',
            name='fan_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
